### ISSUE TITLE
[AWS] Add support to DynamoDB trigger for lambda functions

### ISSUE THREAD

**Issue by aleal** [americanas-go/faas#22]

**Comment by jvitoroc** [comment]
The dynamodb event stream sends the userIdentity field that shows which user originated the event:
https://github.com/aws/aws-lambda-go/blob/e5da494987442caa3749213d5fc56ea6e440bf77/events/dynamodb.go#L58

Would be nice if we populated the cloud event with it.

**Steps:**
Add the field to the following struct:
https://github.com/americanas-go/faas/blob/43de409c94b6a046d46b253da62c3198b3f53355/lambda/event.go#L9
And populate the cloud event with it:
https://github.com/americanas-go/faas/blob/feature/issue-21/lambda/dynamodb.go#L38
